# Declare variables to be passed into your templates.

replicaCount: 2

binanceApi: STRING # Replace
binanceSecret: STRING # Replace

domain: example.com # Replace

fullnameOverride: "cryptoview-app"
containerPort: 5001

image:
  repository: my.registry/path/to/image # Replace
  tag: 0.0.1 # Replace
  pullPolicy: IfNotPresent

imagePullSecrets:
- name: regcred # Create docker-registry secret with your registry credentials

serviceAccount:
  create: true
  name: "cryptoview"

ingress:
  enabled: true

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  averageUtilization: 80